"""Add display_name and avatar_url to users

Revision ID: e66bafce3404
Revises: 20260730_0002
Create Date: 2026-08-30 19:24:01.437320
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e66bafce3404'
down_revision: Union[str, None] = '20260730_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'display_name')
    pass
    # ### end Alembic commands ###
